update

diff --git a/lfskit b/lfskit
--- a/lfskit
+++ b/lfskit
@@ -552,81 +552,38 @@ ENDTEXT
 
 
 EOF
-
-
-}
-
-LFS_CFG_INSTALLER() {
-
-cat > $TGT_LIVE_DISK/boot/lfs.cfg << "EOF"
-
-PROMPT 0
-TIMEOUT 90
-DEFAULT /boot/vesamenu.c32
-MENU BACKGROUND /boot/bootlogo.png
-
-MENU WIDTH 36
-MENU MARGIN 0
-MENU ROWS 8
-MENU HELPMSGROW 14
-MENU TIMEOUTROW 22
-MENU TABMSGROW 24
-MENU CMDLINEROW 24
-MENU HSHIFT 40
-MENU VSHIFT 2
-
-	menu color screen	37;40      #00000000 #00000000 none
-	menu color border	30;44      #00000000 #00000000 none
-	menu color title	1;36;44    #00000000 #00000000 none
-	menu color unsel	37;44      #ff60CA00 #00000000 none
-	menu color hotkey	1;37;44    #ff60CA00 #00000000 none
-	menu color sel		7;37;40    #ffffffff #ff60CA00 none
-	menu color hotsel	1;7;37;40  #ff808080 #ff60CA00 none
-	menu color scrollbar	30;44      #00000000 #00000000 none
-
-	menu color tabmsg	31;40      #aaaaaaaa #00000000 none
-	menu color cmdmark	1;36;40    #ffff0000 #00000000 none
-	menu color cmdline	37;40      #aaaaaaaa #00000000 none
-	menu color pwdborder	30;47      #ffff0000 #00000000 std
-	menu color pwdheader	31;47      #ffff0000 #00000000 std
-	menu color pwdentry	30;47      #ffff0000 #00000000 std
-	menu color timeout_msg	37;40      #aaaaaaaa #00000000 none
-	menu color timeout	1;37;40    #ffaaaaff #00000000 none
-	menu color help		37;40      #aaaaaa00 #00000000 none
-	menu color msg07	37;40      #90ffffff #00000000 std
+if [ "$EMBEDED_INITRD" == "yes" ]; then
+        echo "" >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "LABEL run $LIVEKITNAME" >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "MENU LABEL Run $LIVEKITNAME" >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "KERNEL /boot/vmlinuz" >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "APPEND initrd=/boot/initrfs.img quiet live " >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "" >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "TEXT HELP" >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "	                                  More about currently selected:" >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "" >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "        	                          Run kolomonggo linux live systemd" >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "                	                  and you can install later " >> $TGT_LIVE_DISK/boot/lfs.cfg
+	echo "ENDTEXT" >> $TGT_LIVE_DISK/boot/lfs.cfg
+        echo "" >> $TGT_LIVE_DISK/boot/lfs.cfg
 
 
 
-LABEL run $LIVEKIT_NAME
-MENU LABEL Run $LIVEKIT_NAME
-KERNEL /boot/vmlinuz
-APPEND initrd=/boot/initrfs.img quiet live 
 
-TEXT HELP
-                                          More about currently selected:
-
-                                          Run kolomonggo linux live systemd
-                                          and you can install later 
-ENDTEXT
-
-LABEL run $LIVEKIT_NAME install
-MENU LABEL Run  $LIVEKIT_NAME install
-KERNEL /boot/vmlinuz
-APPEND initrd=/boot/initrfs.img quiet live install
-
-TEXT HELP
-                                          More about currently selected:
-
-                                          Run kolomonggo linux live sysvinit
-                                          and you can install later 
-ENDTEXT
+fi 
 
 
-EOF
 
 
 }
 
+
+
+
+#build_iso(){
+
+
+#}
 
 
 
@@ -956,7 +913,7 @@ exit 0
 
 
 remaster_() {
-clear 
+
 echo "// REMASTERING process "
 echo ""
 echo "  --- CAUTION ! --- "
@@ -1078,6 +1035,19 @@ parse_options() {
 	fi
 }
 
+parse_options_() {
+	
+		while [ "$1" ]; do
+			case "${1}" in
+				--remastering)
+					SETUP_REMASTERING="yes"
+                                        ;;
+				
+			esac
+			shift
+		done
+	
+}
 
 main () {
 	parse_options "$@"
@@ -1130,7 +1100,7 @@ main () {
 ceck_depend() {
 
   echo "checking dependencies ..."
-  echo ""
+
 
  
   if ! [ -x "$(command -v xterm)" ]; then
@@ -1203,6 +1173,8 @@ if [ "$INSTALLER_ENABLED" == "yes" ]; then
          NOCKI_INS="yes"
     fi
 fi
+
+
  sleep 1
 if grep -qw aufs /proc/filesystems; then
   echo "checking AUFS      yes "
@@ -1211,6 +1183,23 @@ else
   echo "checking AUFS      no "
   AUFS_MODULE="no"
 fi
+ sleep 1
+
+if [ "$SETUP_REMASTERING" == "yes" ]; then
+	if [ -f "$KERNEL_FILE" ];
+	then
+   		echo "kernwl $KERNEL_FILE     yes"
+                KERN_INS="yes"
+	else    
+               summary_
+              
+   	       echo "   kernel        $KERNEL_FILE not found."  
+               echo "                 please edit in config or lib/.config "
+               echo ""
+               exit 1
+	fi
+fi 
+
 
 
 sleep 1 
@@ -1327,6 +1316,12 @@ else
         echo "   embeded initrd   no"
 fi
 
+if [ "$KERN_INS" == "yes" ]; then
+        echo "   kernel           $KERNEL_FILE"
+
+else
+        echo "   kernel           not found"
+fi
 
 
 
@@ -1341,7 +1336,8 @@ echo " "
 ####################### main line program #######################
 #################################################################
 
-ceck_depend
+parse_options_ "$@"
+ceck_depend 
 
 
 
@@ -1367,7 +1363,7 @@ ceck_depend
 
     read -rsp $'Press any key to continue...\n' -n1 key
 
-clear
+#clear
 fi
 
 
